#! /bin/bash

base='https://www.beeminder.com/api/v1/'
# user=''
# key=''

goal=$1
date=$2
data=$3
comment=$4

function check_data() {
if [[ ! $data =~ ^-?[0-9]+(\.[0-9]+)?$ ]]
then
    echo "data must be a number" >&2
    exit 3
fi
}

function process_date() {
# get current date
let day=$(date +%-d)
let month=$(date +%-m)

if [[ $date == "^" ]]
then
    # today
    timestamp=$(date -d "${month}/${day}" +%s)
else 
    if [[ $date -gt $day ]]
    then
        # last month
        let month-=1
    fi
    timestamp=$(date -d "${month}/${date}" +%s)
    if [[ $? != 0 ]]
    then
        # invalid date
        exit 2
    fi
fi
}

function check_goal() {
# check if goal exists
goals=$(curl -s "${base}users/${user}.json?auth_token=$key" |sed 's/^.*"goals":\[\(.*\)\].*$/\1/')

if [[ ! $goals =~ \"${goal}\" ]]
then
    echo "Goal '$goal' not found" >&2
    exit 1
fi
}

function submit() {
# submit data
curl -sd "timestamp=${timestamp}&value=${data}&comment=${comment}&auth_token=${key}" "${base}users/${user}/goals/${goal}/datapoints.json" |sed 's/^.*\"status\":\"\([^"]*\)\".*$/\1\n/'
# echo "timestamp=${timestamp}&value=${data}&comment=${comment}&auth_token=${key}" "${base}users/${user}/goals/${goal}/datapoints.json" |sed 's/^.*\"status\":\"\([^"]*\)\".*$/\1\n/'
}

function goal_status() {
# get status
curl -s "${base}users/${user}/goals/${goal}.json?auth_token=${key}" |sed 's/^.*\"headsum\":\"\([^"]*\)\".*$/\1\n/'
}

case $# in
    3|4 )
        check_data 
        process_date 
        check_goal 
        submit 
        exit 0    
    ;;
    1 )
        check_goal
        goal_status
    ;;
    * )
        echo "Usage: $0 <goal> <day> <data> [comment]" >&2
        exit 4
    ;;
esac
