#! /bin/bash

base='https://www.beeminder.com/api/v1/'
# user=''
# key=''


if [[ $# -ne 3 && $# -ne 4 ]]
then
    echo "Usage: $0 <goal> <day> <data> [comment]" >&2
    exit 4
else
    # check data
    if [[ ! $3 =~ ^-?[0-9]+(\.[0-9]+)?$ ]]
    then
        echo "data must be a number" >&2
        exit 3
    fi

    # make date
    let day=$(date +%d)
    let month=$(date +%m)

    if [[ $2 == "^" ]]
    then
        # today
        timestamp=$(date -d "${month}/${day}" +%s)
    else 
        if [[ $2 -gt $day ]]
        then
            # last month
            let month-=1
        fi
        timestamp=$(date -d "${month}/${2}" +%s)
        if [[ $? != 0 ]]
        then
            # invalid date
            exit 2
        fi
    fi

    # check if goal exists
    goals=$(curl -s "${base}users/${user}.json?auth_token=$key" |sed 's/^.*"goals":\[\(.*\)\].*$/\1/')

    if [[ ! $goals =~ \"${1}\" ]]
    then
        echo "Goal '$1' not found" >&2
        exit 1
    fi

    # submit data
    curl -sd "timestamp=${timestamp}&value=${3}&comment=${4}&auth_token=${key}" "${base}users/${user}/goals/${1}/datapoints.json" |sed 's/^.*\"status\":\"\([^"]*\)\".*$/\1\n/'

    # get status
    curl -s "${base}users/${user}/goals/${1}.json?auth_token=${key}" |sed 's/^.*\"headsum\":\"\([^"]*\)\".*$/\1\n/'
    exit 0
fi
